CREATE TABLE IF NOT EXISTS weather_data (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    datatimestamp BIGINT NOT NULL,
    recorded_at DATETIME NOT NULL,
    timeoffset INT,
    conditiontimestamp BIGINT,
    `condition` INT,
    temperature DECIMAL(5,2),
    dewpoint DECIMAL(5,2),
    windchill DECIMAL(5,2),
    wetbulbtemperature DECIMAL(5,2),
    humidity INT,
    airpress_rel DECIMAL(6,2),
    tendency INT,
    precipitation DECIMAL(5,2),
    rainrate DECIMAL(5,2),
    itsraining TINYINT(1),
    windspeed DECIMAL(5,2),
    gustspeed DECIMAL(5,2),
    winddirection INT,
    uv DECIMAL(4,1),
    solar INT,
    brightness INT,
    suntime INT,
    snowheighttimestamp BIGINT,
    snowheight DECIMAL(5,2),
    temp1 DECIMAL(5,2),
    temp2 DECIMAL(5,2),
    temp3 DECIMAL(5,2),
    temp4 DECIMAL(5,2),
    humidity1 INT,
    humidity2 INT,
    humidity3 INT,
    humidity4 INT,
    soilmoisture1 INT,
    soilmoisture2 INT,
    soilmoisture3 INT,
    soilmoisture4 INT,
    leafwetness1 INT,
    leafwetness2 INT,
    indoortemperature DECIMAL(5,2),
    indoorhumidity INT,
    airquality_pm1 DECIMAL(5,2),
    airquality_pm2 DECIMAL(5,2),
    airquality_pm10 DECIMAL(5,2),
    UNIQUE KEY unique_timestamp (datatimestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 